import { DataRoomPackage } from '../../types';
import { getComplianceSummary, getControls, getEvidence } from './soc2Controls';
import { getContractSummary, getContracts, getContractAuditLog } from './contractVault';
import { getRevenueMetrics, getRenewalForecast, getSubscriptions, calculateARR } from './revenueEngine';
import { getOrganizations, getOrgMetrics, getOffboardingRecords } from './orgProvisioning';
import { getRoleStats, getRoleDefinitions, getRBACauditLog } from './rbac';
import { getSecurityPosture, generateSecurityPostureReport, calculateSecurityScore } from './securityPosture';
import { getIntegrationSummary, getAPICredentials, getWebhooks } from './integrationInterfaces';

function generateId(prefix: string): string {
  return `${prefix}_${Date.now()}_${Math.random().toString(36).substr(2, 9)}`;
}

// ============================================
// DATA ROOM PACKAGE GENERATION
// ============================================

export interface DataRoomOptions {
  includeSections: {
    companyOverview: boolean;
    financialSummary: boolean;
    customerContracts: boolean;
    soc2Controls: boolean;
    securityPosture: boolean;
    auditLogs: boolean;
    orgList: boolean;
    revenueMetrics: boolean;
    technicalArchitecture: boolean;
    legalDocuments: boolean;
  };
  dateRange?: {
    start: number;
    end: number;
  };
  redactPII?: boolean;
}

export const DEFAULT_DATA_ROOM_OPTIONS: DataRoomOptions = {
  includeSections: {
    companyOverview: true,
    financialSummary: true,
    customerContracts: true,
    soc2Controls: true,
    securityPosture: true,
    auditLogs: true,
    orgList: true,
    revenueMetrics: true,
    technicalArchitecture: true,
    legalDocuments: true,
  },
  redactPII: true,
};

export async function generateDataRoomPackage(
  generatedBy: string,
  options: DataRoomOptions = DEFAULT_DATA_ROOM_OPTIONS
): Promise<DataRoomPackage> {
  const now = Date.now();

  const pkg: DataRoomPackage = {
    id: generateId('drpkg'),
    generatedAt: now,
    generatedBy,
    version: '1.0.0',
    sections: options.includeSections,
    metadata: {
      generationTimeMs: 0,
      totalItems: 0,
      redacted: options.redactPII || false,
    },
  };

  const startTime = Date.now();

  // Gather data from all services
  if (options.includeSections.soc2Controls) {
    await getComplianceSummary();
  }

  if (options.includeSections.customerContracts) {
    await getContractSummary();
  }

  if (options.includeSections.revenueMetrics) {
    await getRevenueMetrics();
  }

  if (options.includeSections.orgList) {
    await getOrgMetrics();
  }

  if (options.includeSections.securityPosture) {
    await calculateSecurityScore();
  }

  pkg.metadata.generationTimeMs = Date.now() - startTime;

  return pkg;
}

// ============================================
// DATA ROOM REPORT GENERATION
// ============================================

export async function generateDataRoomReport(
  generatedBy: string,
  options: DataRoomOptions = DEFAULT_DATA_ROOM_OPTIONS
): Promise<string> {
  const now = new Date();

  let report = `
================================================================================
                        DUE DILIGENCE DATA ROOM
================================================================================
Generated: ${now.toISOString()}
Generated By: ${options.redactPII ? '[REDACTED]' : generatedBy}
Version: 1.0.0

`;

  // ============================================
  // COMPANY OVERVIEW
  // ============================================
  if (options.includeSections.companyOverview) {
    const orgMetrics = await getOrgMetrics();

    report += `
================================================================================
SECTION 1: COMPANY OVERVIEW
================================================================================

Organization Summary:
---------------------
Total Organizations: ${orgMetrics.total}
Active Organizations: ${orgMetrics.byStatus.active}
Pending Organizations: ${orgMetrics.byStatus.pending}
Pending Provisioning Requests: ${orgMetrics.pendingRequests}
Active Offboardings: ${orgMetrics.activeOffboardings}

Organization Tier Distribution:
- Personal: ${orgMetrics.byTier.personal}
- Family: ${orgMetrics.byTier.family}
- Pilot: ${orgMetrics.byTier.pilot}
- Enterprise: ${orgMetrics.byTier.enterprise}

`;
  }

  // ============================================
  // FINANCIAL SUMMARY
  // ============================================
  if (options.includeSections.financialSummary) {
    const revenueMetrics = await getRevenueMetrics();
    const arr = await calculateARR();
    const renewalForecast = await getRenewalForecast(90);

    report += `
================================================================================
SECTION 2: FINANCIAL SUMMARY
================================================================================

Revenue Metrics:
----------------
Monthly Recurring Revenue (MRR): $${revenueMetrics.mrr.toLocaleString()}
Annual Recurring Revenue (ARR): $${revenueMetrics.arr.toLocaleString()}

ARR by Tier:
- Personal: $${arr.byTier.personal.toLocaleString()}
- Family: $${arr.byTier.family.toLocaleString()}
- Pilot: $${arr.byTier.pilot.toLocaleString()}
- Enterprise: $${arr.byTier.enterprise.toLocaleString()}

Subscription Metrics:
- Active Subscriptions: ${revenueMetrics.activeSubscriptions}
- Total Seats: ${revenueMetrics.totalSeats}
- Average Revenue Per Seat: $${revenueMetrics.averageRevenuePerSeat}

This Month:
- New Revenue: $${revenueMetrics.newRevenueThisMonth.toLocaleString()}
- Churned Revenue: $${revenueMetrics.churnThisMonth.toLocaleString()}
- Net Revenue Change: $${revenueMetrics.netRevenueChange.toLocaleString()}

Renewal Forecast (Next 90 Days):
- Total Renewals: ${renewalForecast.length}
- High Risk: ${renewalForecast.filter(r => r.riskLevel === 'high').length}
- Medium Risk: ${renewalForecast.filter(r => r.riskLevel === 'medium').length}
- Low Risk: ${renewalForecast.filter(r => r.riskLevel === 'low').length}

`;
  }

  // ============================================
  // CUSTOMER CONTRACTS
  // ============================================
  if (options.includeSections.customerContracts) {
    const contractSummary = await getContractSummary();

    report += `
================================================================================
SECTION 3: CUSTOMER CONTRACTS
================================================================================

Contract Summary:
-----------------
Total Contracts: ${contractSummary.total}
Total Annual Contract Value: $${contractSummary.totalAnnualValue.toLocaleString()}
Auto-Renewal Contracts: ${contractSummary.autoRenewCount}

Contracts by Status:
- Active: ${contractSummary.byStatus.active}
- Signed: ${contractSummary.byStatus.signed}
- Draft: ${contractSummary.byStatus.draft}
- Negotiating: ${contractSummary.byStatus.negotiating}
- Expired: ${contractSummary.byStatus.expired}
- Terminated: ${contractSummary.byStatus.terminated}

Contracts by Type:
- Master Service Agreement (MSA): ${contractSummary.byType.msa}
- Statement of Work (SOW): ${contractSummary.byType.sow}
- Data Processing Agreement (DPA): ${contractSummary.byType.dpa}
- Business Associate Agreement (BAA): ${contractSummary.byType.baa}
- Non-Disclosure Agreement (NDA): ${contractSummary.byType.nda}
- Pilot Agreement: ${contractSummary.byType.pilot}
- Enterprise License: ${contractSummary.byType.enterprise}
- Amendments: ${contractSummary.byType.amendment}

Upcoming Expirations:
- Expiring in 30 days: ${contractSummary.expiringIn30Days}
- Expiring in 90 days: ${contractSummary.expiringIn90Days}

`;
  }

  // ============================================
  // SOC2 CONTROLS
  // ============================================
  if (options.includeSections.soc2Controls) {
    const complianceSummary = await getComplianceSummary();

    report += `
================================================================================
SECTION 4: SOC2 COMPLIANCE CONTROLS
================================================================================

Compliance Summary:
-------------------
Total Controls: ${complianceSummary.total}
Implementation Progress: ${complianceSummary.percentComplete}%

Control Status:
- Implemented: ${complianceSummary.implemented}
- Partial: ${complianceSummary.partial}
- Planned: ${complianceSummary.planned}
- Not Applicable: ${complianceSummary.notApplicable}

Controls by Category:
- Common Criteria (CC): ${complianceSummary.byCategory.CC.implemented}/${complianceSummary.byCategory.CC.total} implemented
- Availability (A): ${complianceSummary.byCategory.A.implemented}/${complianceSummary.byCategory.A.total} implemented
- Confidentiality (C): ${complianceSummary.byCategory.C.implemented}/${complianceSummary.byCategory.C.total} implemented
- Processing Integrity (PI): ${complianceSummary.byCategory.PI.implemented}/${complianceSummary.byCategory.PI.total} implemented
- Privacy (P): ${complianceSummary.byCategory.P.implemented}/${complianceSummary.byCategory.P.total} implemented

Overdue Reviews: ${complianceSummary.overdueReviews}

`;
  }

  // ============================================
  // SECURITY POSTURE
  // ============================================
  if (options.includeSections.securityPosture) {
    const securityReport = await generateSecurityPostureReport();
    report += `
================================================================================
SECTION 5: SECURITY POSTURE
================================================================================
${securityReport}

`;
  }

  // ============================================
  // ORGANIZATION LIST
  // ============================================
  if (options.includeSections.orgList) {
    const orgs = await getOrganizations();
    const activeOrgs = orgs.filter(o => o.status === 'active');

    report += `
================================================================================
SECTION 6: CUSTOMER LIST
================================================================================

Active Customers: ${activeOrgs.length}

Customer Breakdown:
-------------------
`;

    for (const org of activeOrgs) {
      report += `
- ${options.redactPII ? '[REDACTED]' : org.displayName}
  Tier: ${org.tier}
  Jurisdiction: ${org.jurisdictionCode}
  Activated: ${org.activatedAt ? new Date(org.activatedAt).toISOString().split('T')[0] : 'N/A'}
`;
    }
  }

  // ============================================
  // AUDIT LOGS SUMMARY
  // ============================================
  if (options.includeSections.auditLogs) {
    const rbacAudit = await getRBACauditLog();
    const contractAudit = await getContractAuditLog();

    report += `
================================================================================
SECTION 7: AUDIT LOG SUMMARY
================================================================================

RBAC Audit Events (Last 30 Days):
---------------------------------
Total Events: ${rbacAudit.length}
- Role Assignments: ${rbacAudit.filter(e => e.action === 'role_assigned').length}
- Role Revocations: ${rbacAudit.filter(e => e.action === 'role_revoked').length}
- Permission Checks (Denied): ${rbacAudit.filter(e => e.action === 'permission_check_denied').length}

Contract Audit Events (Last 30 Days):
-------------------------------------
Total Events: ${contractAudit.length}
- Contracts Created: ${contractAudit.filter(e => e.action === 'contract_created').length}
- Contracts Signed: ${contractAudit.filter(e => e.action === 'contract_signed').length}
- PDF Accessed: ${contractAudit.filter(e => e.action === 'pdf_accessed').length}

`;
  }

  // ============================================
  // FOOTER
  // ============================================
  report += `
================================================================================
                            END OF DATA ROOM REPORT
================================================================================

This report was automatically generated by Orbital Data Room Generator.
All data is current as of the generation timestamp.

For questions or additional documentation requests, contact your account manager.

CONFIDENTIAL - FOR AUTHORIZED RECIPIENTS ONLY
`;

  return report;
}

// ============================================
// DATA ROOM EXPORT FORMATS
// ============================================

export async function exportDataRoomJSON(
  generatedBy: string,
  options: DataRoomOptions = DEFAULT_DATA_ROOM_OPTIONS
): Promise<Record<string, unknown>> {
  const dataRoom: Record<string, unknown> = {
    metadata: {
      generatedAt: new Date().toISOString(),
      generatedBy: options.redactPII ? '[REDACTED]' : generatedBy,
      version: '1.0.0',
      sections: options.includeSections,
    },
  };

  if (options.includeSections.companyOverview) {
    dataRoom.companyOverview = {
      organizations: await getOrgMetrics(),
    };
  }

  if (options.includeSections.financialSummary) {
    dataRoom.financialSummary = {
      revenueMetrics: await getRevenueMetrics(),
      arr: await calculateARR(),
      renewalForecast: await getRenewalForecast(90),
      subscriptions: options.redactPII ? [] : await getSubscriptions(),
    };
  }

  if (options.includeSections.customerContracts) {
    dataRoom.customerContracts = {
      summary: await getContractSummary(),
      contracts: options.redactPII ? [] : await getContracts(),
    };
  }

  if (options.includeSections.soc2Controls) {
    dataRoom.soc2Controls = {
      summary: await getComplianceSummary(),
      controls: await getControls(),
      evidence: await getEvidence(),
    };
  }

  if (options.includeSections.securityPosture) {
    dataRoom.securityPosture = {
      posture: await getSecurityPosture(),
      score: await calculateSecurityScore(),
    };
  }

  if (options.includeSections.orgList) {
    const orgs = await getOrganizations();
    dataRoom.organizations = options.redactPII
      ? orgs.map(o => ({ ...o, displayName: '[REDACTED]', primaryContact: undefined }))
      : orgs;
  }

  if (options.includeSections.auditLogs) {
    dataRoom.auditLogs = {
      rbac: await getRBACauditLog(),
      contracts: await getContractAuditLog(),
    };
  }

  return dataRoom;
}

// ============================================
// DATA ROOM SECTION GENERATORS
// ============================================

export async function generateExecutiveSummary(): Promise<string> {
  const orgMetrics = await getOrgMetrics();
  const revenueMetrics = await getRevenueMetrics();
  const complianceSummary = await getComplianceSummary();
  const securityScore = await calculateSecurityScore();
  const contractSummary = await getContractSummary();

  return `
EXECUTIVE SUMMARY
=================
Generated: ${new Date().toISOString()}

KEY METRICS AT A GLANCE
-----------------------
Annual Recurring Revenue: $${revenueMetrics.arr.toLocaleString()}
Active Customers: ${orgMetrics.byStatus.active}
Total Contracted Value: $${contractSummary.totalAnnualValue.toLocaleString()}

COMPLIANCE STATUS
-----------------
SOC2 Controls: ${complianceSummary.percentComplete}% implemented
Security Score: ${securityScore.overall}/100

GROWTH INDICATORS
-----------------
Active Subscriptions: ${revenueMetrics.activeSubscriptions}
Net Revenue Change (MTD): $${revenueMetrics.netRevenueChange.toLocaleString()}

${securityScore.recommendations.length > 0 ? `
KEY RECOMMENDATIONS
-------------------
${securityScore.recommendations.map((r, i) => `${i + 1}. ${r}`).join('\n')}
` : ''}
`;
}

export async function generateComplianceCertificate(): Promise<string> {
  const complianceSummary = await getComplianceSummary();
  const securityScore = await calculateSecurityScore();
  const posture = await getSecurityPosture();

  return `
================================================================================
                    COMPLIANCE ATTESTATION CERTIFICATE
================================================================================

Date: ${new Date().toISOString()}
Certificate ID: ${generateId('cert')}

This certificate attests to the current compliance status of Orbital.

SOC2 TRUST SERVICES CRITERIA
----------------------------
Implementation Status: ${complianceSummary.percentComplete}%
Controls Implemented: ${complianceSummary.implemented} of ${complianceSummary.total}

Security Category (CC): ${complianceSummary.byCategory.CC.implemented}/${complianceSummary.byCategory.CC.total}
Availability (A): ${complianceSummary.byCategory.A.implemented}/${complianceSummary.byCategory.A.total}
Confidentiality (C): ${complianceSummary.byCategory.C.implemented}/${complianceSummary.byCategory.C.total}
Processing Integrity (PI): ${complianceSummary.byCategory.PI.implemented}/${complianceSummary.byCategory.PI.total}
Privacy (P): ${complianceSummary.byCategory.P.implemented}/${complianceSummary.byCategory.P.total}

SECURITY POSTURE SCORE
----------------------
Overall Score: ${securityScore.overall}/100

Component Scores:
- Encryption: ${securityScore.encryption}/100
- Backup & Recovery: ${securityScore.backup}/100
- Access Controls: ${securityScore.accessControls}/100
- Vulnerability Management: ${securityScore.vulnerabilityManagement}/100
- Incident Response: ${securityScore.incidentResponse}/100
- Audit Logging: ${securityScore.auditLogging}/100

KEY SECURITY CONTROLS
---------------------
- Encryption at Rest: ${posture.encryption.atRest.enabled ? 'Enabled' : 'Disabled'} (${posture.encryption.atRest.algorithm})
- Encryption in Transit: ${posture.encryption.inTransit.enabled ? 'Enabled' : 'Disabled'} (${posture.encryption.inTransit.protocol} ${posture.encryption.inTransit.minVersion})
- MFA Required: ${posture.accessControls.mfaRequired ? 'Yes' : 'No'}
- Audit Logging: ${posture.auditLogging.enabled ? 'Enabled' : 'Disabled'}

================================================================================
This certificate is automatically generated and reflects the current state of
compliance controls. It does not constitute a formal SOC2 audit report.
================================================================================
`;
}
