devices([
  "iPhone 16 Pro Max",
  "iPhone 15 Pro Max",
  "iPhone 14 Pro Max"
])
languages(["en-US"])
output_directory("./fastlane/screenshots")
clear_previous_screenshots(true)
workspace("./ios/Orbital.xcworkspace")
scheme("Orbital")
stop_after_first_error(false)
override_status_bar(true)
