/**
 * Orbital Load Test Configuration
 *
 * Shared configuration for k6 stress tests.
 * Uses local Supabase by default to avoid rate limits.
 */

// Environment detection
const isLocal = __ENV.SUPABASE_URL?.includes('localhost') ||
                __ENV.SUPABASE_URL?.includes('127.0.0.1') ||
                !__ENV.SUPABASE_URL;

// Default to local Supabase if no URL provided
export const config = {
  supabaseUrl: __ENV.SUPABASE_URL || 'http://localhost:54321',
  supabaseAnonKey: __ENV.SUPABASE_ANON_KEY || 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZS1kZW1vIiwicm9sZSI6ImFub24iLCJleHAiOjE5ODM4MTI5OTZ9.CRXP1A7WOeoJeXxjNni43kdQwgnWNReilDMblYTn_I0',
  supabaseServiceKey: __ENV.SUPABASE_SERVICE_KEY || 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZS1kZW1vIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImV4cCI6MTk4MzgxMjk5Nn0.EGIM96RAZx35lJzdJsyH-qQwv8Hdp7fsn3W0YpN81IU',
  isLocal,
};

// Thresholds - stricter for local, more lenient for remote
export const thresholds = {
  // Error rate must be < 0.5%
  'http_req_failed': ['rate<0.005'],

  // Latency thresholds
  'http_req_duration': isLocal
    ? ['p(95)<800', 'p(99)<1500']  // Local: p95 < 800ms, p99 < 1.5s
    : ['p(95)<2000', 'p(99)<4000'], // Remote: p95 < 2s, p99 < 4s

  // Custom metrics
  'rls_violations': ['count==0'],
  'auth_failures': ['rate<0.01'],
};

// API endpoints
export const endpoints = {
  // PostgREST endpoints
  capacityLogs: '/rest/v1/capacity_logs',
  patterns: '/rest/v1/patterns',
  userProfiles: '/rest/v1/user_profiles',

  // RPC endpoints
  joinCircle: '/rest/v1/rpc/join_circle',
  logCapacity: '/rest/v1/rpc/log_capacity',
  getPatterns: '/rest/v1/rpc/get_patterns',
};

// Test user JWT file (generated by seed script)
export const JWT_FILE = __ENV.JWT_FILE || './tests/load/test-users.json';

// Default headers for Supabase
export function getHeaders(jwt) {
  return {
    'Content-Type': 'application/json',
    'apikey': config.supabaseAnonKey,
    'Authorization': `Bearer ${jwt}`,
    'Prefer': 'return=representation',
  };
}

export function getServiceHeaders() {
  return {
    'Content-Type': 'application/json',
    'apikey': config.supabaseServiceKey,
    'Authorization': `Bearer ${config.supabaseServiceKey}`,
    'Prefer': 'return=representation',
  };
}
